"""add_phonepe_fields

Revision ID: 216658c1d629
Revises: 5c4ffa457c11
Create Date: 2025-11-24 16:47:12.954989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216658c1d629'
down_revision: Union[str, Sequence[str], None] = '5c4ffa457c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add PhonePe columns to payments table
    op.add_column('payments', sa.Column('phonepe_order_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('phonepe_payment_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('transaction_id', sa.String(), nullable=True))
    
    # SQLite doesn't support ALTER COLUMN, so skip nullable change for razorpay_order_id
    # It won't cause issues since we're adding PhonePe as alternative
    
    # Add PhonePe columns to reservations table
    op.add_column('reservations', sa.Column('phonepe_order_id', sa.String(), nullable=True))
    op.add_column('reservations', sa.Column('phonepe_payment_id', sa.String(), nullable=True))
    op.add_column('reservations', sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=True))
    op.add_column('reservations', sa.Column('payment_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove PhonePe columns from reservations
    op.drop_column('reservations', 'payment_type')
    op.drop_column('reservations', 'payment_status')
    op.drop_column('reservations', 'phonepe_payment_id')
    op.drop_column('reservations', 'phonepe_order_id')
    
    # Remove PhonePe columns from payments
    op.drop_column('payments', 'transaction_id')
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'phonepe_payment_id')
    op.drop_column('payments', 'phonepe_order_id')
    # ### end Alembic commands ###
