"""add_author_field_to_books

Revision ID: 426e17b48559
Revises: c9773e19200d
Create Date: 2025-09-11 23:59:45.334352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426e17b48559'
down_revision: Union[str, Sequence[str], None] = 'c9773e19200d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('author', sa.String(), nullable=True))
    op.create_index(op.f('ix_books_author'), 'books', ['author'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_author'), table_name='books')
    op.drop_column('books', 'author')
    # ### end Alembic commands ###
