"""change_rental_price_per_day_to_weekly_fee

Revision ID: 5c4ffa457c11
Revises: 1f1257f5e605
Create Date: 2025-10-22 14:20:03.112833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4ffa457c11'
down_revision: Union[str, Sequence[str], None] = '1f1257f5e605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('weekly_fee', sa.Float(), nullable=True))
    op.drop_column('books', 'rental_price_per_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('rental_price_per_day', sa.FLOAT(), nullable=True))
    op.drop_column('books', 'weekly_fee')
    # ### end Alembic commands ###
