"""Update Book model - remove author/genre, add search_text

Revision ID: 648d624bbb85
Revises: 08be1bbaa82a
Create Date: 2025-08-15 12:32:28.191435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648d624bbb85'
down_revision: Union[str, Sequence[str], None] = '08be1bbaa82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('search_text', sa.Text(), nullable=False))
    op.create_index(op.f('ix_books_search_text'), 'books', ['search_text'], unique=False)
    op.drop_column('books', 'author')
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.VARCHAR(), nullable=True))
    op.add_column('books', sa.Column('author', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_books_search_text'), table_name='books')
    op.drop_column('books', 'search_text')
    # ### end Alembic commands ###
