"""convert_genre_to_tags_and_remove_user_type

Revision ID: c9773e19200d
Revises: 1f1257f5e605
Create Date: 2025-09-11 18:55:02.593778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9773e19200d'
down_revision: Union[str, Sequence[str], None] = '1f1257f5e605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('tags', sa.Text(), nullable=True))
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.VARCHAR(length=7), nullable=False))
    op.drop_column('books', 'tags')
    # ### end Alembic commands ###
